### ISSUE TITLE
Not really an issue but just a question

### ISSUE THREAD

**Issue by tylerbestww** [DO-Ui/BombpartyBot#10]
![image](https://user-images.githubusercontent.com/102341126/202894641-efc6c326-4048-41fa-bc6f-32f23227f2ea.png)

I dont really understand what this line here does in your Main.java file, I tried running the 

"int fail = (int) (Math.random() * (1000 - 0) + 0);" and it never gives me anything close to 

fail == 2

I was just wondering how this line of code works. Sorry for the inconvenience caused I'm trying to learn more as well.

**Comment by DO-Ui** [comment]
In Java, to specify a range of numbers when using `Math.random`  the syntax is `int rand = (int)(Math.random() * range) + min;` where range is the max value and min is the smallest value. The code you showed is 0-1000 so you would have a 1/1000 chance of getting 2. 

Source: https://www.geeksforgeeks.org/java-math-random-method-examples/

**Comment by DO-Ui** [comment]
It may be a good idea to search online for help before resorting to asking others.

**Comment by tylerbestww** [comment]
Man thanks a lot, I appreciate it.
