### ISSUE TITLE
Problem with running Main.java

### ISSUE THREAD

**Issue by hnatien** [DO-Ui/BombpartyBot#2]
Hi, I can't run the Main.java for some reason. Which program should I use to run it?

**Comment by DO-Ui** [comment]
You should run the program with java.
I provided a link to download java on the main page: https://www.oracle.com/java/technologies/javase-jdk16-downloads.html

**Comment by DO-Ui** [comment]
To open a terminal (assuming you are using windows) simply click on the top bar and then type "cmd"

A tutorial can be found at https://helpdeskgeek.com/how-to/open-command-prompt-folder-windows-explorer/

**Comment by DO-Ui** [comment]
I've updated the repo to include a JAR file this should make it much easier to run the bot
