### ISSUE TITLE
Windows OS error when running on terminal

### ISSUE THREAD

**Issue by limzk126** [DO-Ui/BombpartyBot#5]
chromedriver is update to date with chrome version.

![image](https://user-images.githubusercontent.com/88614036/156872924-7adc13d7-41af-4c2b-9baa-07e509179cbe.png)

**Comment by DO-Ui** [comment]
This seems to be a duplicate of issue #4 try and replace the "chromedriver" from the "mac" folder with the chromedriver.exe with the ".exe" removed. Im not 100% sure why or if this works but it seemed to work for the other issue.
