### ISSUE TITLE
wordlist autoupdate

### ISSUE THREAD

**Issue by SakonLight90** [DO-Ui/BombpartyBot#8]
Just an Idea, to make the bot auto delete words from the file that the game does not accept?

**Comment by DO-Ui** [comment]
It could be possible to implement in a future release although I don't really plan on doing too many major changes to the bot for now.

**Comment by DO-Ui** [comment]
I just took a look at the jlkm.fun website and I don't believe there is a way to consistently detect when you have an incorrect answer. Manually trimming the wordlist would also work, I might update the wordlist to be only valid words at some point.
