### ISSUE TITLE
Bombparty-bot.jar seems to close instantly upon opening with double click

### ISSUE THREAD

**Issue by tylerbestww** [DO-Ui/BombpartyBot#9]

**Comment by DO-Ui** [comment]
.jar files are not meant to be run with a double-click, as mentioned in the Readme

> open a terminal or cmd in the folder and run
> ```java -jar Bombparty-bot.jar```

This should open a chrome window with the jklm website open, provided you downloaded the correct version of chromedriver

**Comment by tylerbestww** [comment]
![Screenshot_20221119_095455](https://user-images.githubusercontent.com/102341126/202828853-83c026c1-4a69-4eec-9a8b-d57183798463.png)

Do I have to downgrade my chrome version?

**Comment by DO-Ui** [comment]
You need to upgrade your chromedriver version to match the version found at chrome://about in your chrome browser

**Comment by DO-Ui** [comment]
For your major chrome version (107) the download link can be found here: https://chromedriver.storage.googleapis.com/index.html?path=107.0.5304.62/ (Make sure to get the windows version)
Other versions can be found here:
https://chromedriver.chromium.org/downloads

**Comment by DO-Ui** [comment]
Once the correct chromedriver is downloaded, replace `chromedriver.exe` in the `windows` folder with the downloaded file

**Comment by tylerbestww** [comment]
Ah, replacing the chromedriver.exe worked! Thanks a lot. Mind explaining why replacing chromedriver.exe in the windows folder solved the problem?

**Comment by DO-Ui** [comment]
My code searches the `windows` folder for the required chromedriver.exe dependency and assumes it is the correct version. In this case, it was the wrong version and replacing it manually fixed it.
